services:
  # Le serveur Web Django
  web:
    build: .
    volumes:
      - .:/app
      - data_volume:/app/data
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    command: python backend/manage.py runserver 0.0.0.0:8000

  # Le service Pipeline (pour lancer run_pipeline.py)
  pipeline:
    build: .
    volumes:
      - .:/app
      - data_volume:/app/data
    env_file:
      - .env
    profiles: ["pipeline"] # Permet de ne le lancer que sur demande
    command: python run_pipeline.py

  # Ollama conteneurisé (IA Locale)
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_storage:/root/.ollama
    ports:
      - "11434:11434"

volumes:
  data_volume:      # Pour les bases JSON et les vecteurs
  ollama_storage:   # Pour les modèles Llama
