TRANSLATIONS = {
    'Français': {
        'nav_anime': '📺 Anime',
        'nav_manga': '📖 Manga',
        'nav_char': '🎭 Persos',
        'nav_paradox': '🧩 Paradoxe',
        'nav_archetypist': '🎬 Archetypiste',
        'nav_undercover': '🕵️ Undercover',
        'settings_title': 'Paramètres',
        'settings_lang': '🌍 Langue de l\'IA & Interface',
        'settings_theme': '🌓 Thème de l\'interface',
        'theme_light': 'Clair',
        'theme_dark': 'Sombre',
        'theme_auto': 'Auto',
        'settings_dark': 'Mode Sombre',
        'index_welcome': 'Bienvenue sur Animetix',
        'index_lead': 'L\'IA au service de votre culture Otaku.',
        'btn_play': 'Jouer maintenant',
        'btn_guess': 'Tenter ma chance',
        'btn_reveal': 'Révéler l\'indice',
        'btn_abandon': 'Abandonner',
        'difficulty': 'Difficulté',
        'diff_easy': 'Facile',
        'diff_normal': 'Normal',
        'diff_hard': 'Difficile',
        'diff_impossible': 'Impossible',
        'placeholder_guess': 'Entrez un titre...',
        'game_over_win': 'Félicitations ! Vous avez trouvé :',
        'game_over_loss': 'Dommage ! C\'était :',
        'sidebar_info': 'La langue modifie l\'interface et les textes générés par l\'IA.',
        'mode_classic_title': 'Animetix Classic',
        'mode_classic_desc': 'Trouvez l\'œuvre secrète en utilisant la similarité sémantique de vos propositions.',
        'mode_archetypist_title': 'Story Archetypist',
        'mode_archetypist_desc': 'Fusionnez deux univers radicalement différents en un seul scénario original généré par l\'IA.',
        'mode_paradox_title': 'Le Paradoxe',
        'mode_paradox_desc': 'L\'IA a fusionné deux œuvres secrètes. Saurez-vous identifier l\'intrus parmi les propositions ?',
        'mode_undercover_title': 'Undercover Party',
        'mode_undercover_desc': 'Jeu de société local : un infiltré a un mot différent. Débattez et éliminez-le !',
        'btn_start_game': 'Lancer une partie',
        'btn_start_fusion': 'Lancer la Fusion',
        'btn_find_intruder': 'Trouver l\'Intrus',
        'btn_start_party': 'Lancer une Soirée',
        'hints_available': 'Indices disponibles',
        'reasoning_title': 'Raisonnement de l\'IA',
        'hint_locked': 'Débloqué à',
        'hint_guesses': 'essais',
        'hint_poster': 'Poster flouté',
        'hint_rec': 'Recommandation proche',
        'hint_chars': 'Personnages présents',
        'hint_words': 'Mots-clés de l\'œuvre',
        'hint_vibe': 'Indice mystère (IA)',
        'hint_scenario': 'Scénario Mystère (IA)',
        'hint_origin': 'Œuvre d\'origine',
        'hint_sim': 'Personnage similaire',
        'table_guess': 'Proposition',
        'table_score': 'Score',
        'table_temp': 'Température',
        'paradox_question': 'Lequel est l\'intrus ?',
        'paradox_win': 'Bien joué ! C\'était bien l\'intrus.',
        'paradox_loss': 'Perdu ! L\'intrus était :',
        'undercover_setup_title': 'Configuration Undercover',
        'undercover_players': 'Nombre de joueurs',
        'undercover_start': 'Commencer la partie',
        'undercover_clue': 'Indice commun',
        'undercover_role_reveal': 'Cliquez sur un joueur pour voir son rôle',
        'undercover_civil': 'Civil',
        'undercover_spy': 'Infiltré',
        'archetypist_generate': 'Générer un autre scénario',
        'archetypist_select': 'Choisissez deux éléments à fusionner',
        'btn_back': 'Retour',
        'footer_rights': '© 2026 Animetix. Tous droits réservés.',
        'footer_built': 'Moteur IA par MissawB',
        'footer_tech': 'Propulsé par',
        'footer_status': 'Serveurs opérationnels',
    },
    'English': {
        'nav_anime': '📺 Anime',
        'nav_manga': '📖 Manga',
        'nav_char': '🎭 Characters',
        'nav_paradox': '🧩 Paradox',
        'nav_archetypist': '🎬 Archetypist',
        'nav_undercover': '🕵️ Undercover',
        'settings_title': 'Settings',
        'settings_lang': '🌍 AI & UI Language',
        'settings_theme': '🌓 Interface Theme',
        'theme_light': 'Light',
        'theme_dark': 'Dark',
        'theme_auto': 'Auto',
        'settings_dark': 'Dark Mode',
        'index_welcome': 'Welcome to Animetix',
        'index_lead': 'AI-powered tools for your Otaku culture.',
        'btn_play': 'Play Now',
        'btn_guess': 'Make a guess',
        'btn_reveal': 'Reveal hint',
        'btn_abandon': 'Give up',
        'difficulty': 'Difficulty',
        'diff_easy': 'Easy',
        'diff_normal': 'Normal',
        'diff_hard': 'Hard',
        'diff_impossible': 'Impossible',
        'placeholder_guess': 'Enter a title...',
        'game_over_win': 'Congratulations! You found:',
        'game_over_loss': 'Too bad! It was:',
        'sidebar_info': 'Language affects both the UI and AI-generated texts.',
        'mode_classic_title': 'Animetix Classic',
        'mode_classic_desc': 'Find the secret work using semantic similarity of your guesses.',
        'mode_archetypist_title': 'Story Archetypist',
        'mode_archetypist_desc': 'Merge two radically different universes into one original AI-generated scenario.',
        'mode_paradox_title': 'The Paradox',
        'mode_paradox_desc': 'The AI has merged two secret works. Can you identify the intruder among the suggestions?',
        'mode_undercover_title': 'Undercover Party',
        'mode_undercover_desc': 'Local party game: an undercover player has a different word. Debate and eliminate them!',
        'btn_start_game': 'Start Game',
        'btn_start_fusion': 'Start Fusion',
        'btn_find_intruder': 'Find the Intruder',
        'btn_start_party': 'Start a Party',
        'hints_available': 'Available Hints',
        'hint_locked': 'Unlocked at',
        'hint_guesses': 'guesses',
        'hint_poster': 'Blurred Poster',
        'hint_rec': 'Similar Recommendation',
        'hint_chars': 'Key Characters',
        'hint_words': 'Thematic Keywords',
        'hint_vibe': 'Mystery Hint (AI)',
        'hint_origin': 'Original Work',
        'hint_sim': 'Similar Character',
        'table_guess': 'Guess',
        'table_score': 'Score',
        'table_temp': 'Temperature',
        'paradox_question': 'Which one is the intruder?',
        'paradox_win': 'Well done! That was indeed the intruder.',
        'paradox_loss': 'Lost! The intruder was:',
        'undercover_setup_title': 'Undercover Setup',
        'undercover_players': 'Number of players',
        'undercover_start': 'Start Game',
        'undercover_clue': 'Common Clue',
        'undercover_role_reveal': 'Click on a player to reveal their role',
        'undercover_civil': 'Civilian',
        'undercover_spy': 'Undercover',
        'archetypist_generate': 'Generate another scenario',
        'archetypist_select': 'Choose two items to merge',
        'btn_back': 'Back',
        'footer_rights': '© 2026 Animetix. All rights reserved.',
        'footer_built': 'AI Engine by MissawB',
        'footer_tech': 'Powered by',
        'footer_status': 'All systems operational',
    }
}
